import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "../lib/authProvider";
import Header from '../components/Header';
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>

      <body className="min-h-full flex flex-col">

        <AuthProvider>
          <Header />

          <Navigation />

          <main className="min-h-screen flex flex-col m-2 rounded-md neon-cyan gradient-border">
            {children}
          </main>


          <Footer />
        </AuthProvider>

      </body>
    </html>
  );
}